# Generated by Django 6.0.1 on 2026-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='review_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
