# Generated by Django 5.0 on 2026-03-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_orders_num_movie_review_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithMostComment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.review',),
        ),
    ]
